import Head from "next/head";
import Link from "next/link";
import React from "react";
import MyAppBar from "../components/myAppBar";
import SearchAnimeWithAnilist from "../components/searchAnimeWithAnilist";
import styles from "../styles/Home.module.css";

const Home = () => {
  return (
    <div
      style={{
        display: "flex",
        justifyContent: "center",
        alignItems: "center",
        backgroundColor: "#116466",
        minHeight: "100vh",
      }}
    >
      <div>
        <Head>
          <title>MALAPI EXPRESS ENTRY POINT</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className={styles.main}>
          <MyAppBar />
          <Link href="/malapi">
            <h2>Click here and Search Anime!</h2>
          </Link>
          <SearchAnimeWithAnilist />
          {/* <GetDetailWithAnilist /> */}
        </main>
      </div>
    </div>
  );
};

export default Home;
